// ==================================================
// PLAYABLE PIANO NOTES
// ==================================================

export const NOTES =
  Object.freeze([

    // Octave 4
    "C4",
    "C#4",
    "D4",
    "D#4",
    "E4",
    "F4",
    "F#4",
    "G4",
    "G#4",
    "A4",
    "A#4",
    "B4",

    // Octave 5
    "C5",
    "C#5",
    "D5",
    "D#5",
    "E5",
    "F5",
    "F#5",
    "G5",
    "G#5",
    "A5",
    "A#5",
    "B5"

  ]);


// ==================================================
// RANDOM NOTE
// ==================================================

export function getRandomNote() {

  const randomIndex =
    Math.floor(
      Math.random() *
      NOTES.length
    );

  return NOTES[
    randomIndex
  ];
}


// ==================================================
// CHART NOTE HELPER
// ==================================================

function createChartNote(
  beat,
  note,
  holdBeats
) {

  return Object.freeze({
    beat,
    note,

    /*
     * 0 for a tap. Anything more is a
     * long note the player holds down
     * for that many beats.
     */
    holdBeats:
      holdBeats || 0
  });
}


/*
 * Long notes.
 *
 * A note becomes a long note when the
 * music holds that sound, which shows
 * up as a long gap before the next
 * note. The hold ends short of the next
 * note, leaving time to move to the
 * next key.
 *
 * The charts generated from audio need
 * a bigger gap than Für Elise, whose
 * held notes come from the score and
 * are shorter.
 */
const MAX_HOLD_BEATS = 4;


function holdLength(
  beat,
  nextBeat,
  minGapBeats,
  releaseGapBeats
) {
  const gap =
    nextBeat - beat;


  if (
    !Number.isFinite(gap) ||
    gap < minGapBeats
  ) {
    return 0;
  }


  return Math.min(
    gap - releaseGapBeats,
    MAX_HOLD_BEATS
  );
}


// ==================================================
// CHART HELPER
// ==================================================

/*
 * Converts a list of [beat, note] pairs
 * into a frozen chart.
 *
 * The charts below were generated from
 * the audio by tools/generate-charts.py:
 *
 * - Notes are placed on beats and half
 *   beats where the track has a real hit,
 *   strongest hits first, so quiet parts
 *   of a song get fewer notes.
 * - Each note's pitch is the strongest
 *   pitch heard in the track at that
 *   moment, limited to the song's key so
 *   whatever the player plays fits the
 *   music, and kept close to the note
 *   before it.
 * - Medium contains every Easy note and
 *   Hard contains every Medium note.
 * - On Hard, a half-beat gap is always
 *   followed by at least a full beat:
 *   quick notes come in pairs, not
 *   streams.
 * - Notes with a long gap after them
 *   become long notes to hold down.
 */
function buildChart(
  pairs
) {
  return Object.freeze(
    pairs.map(
      ([beat, note], index) =>
        createChartNote(
          beat,
          note,
          holdLength(
            beat,

            index + 1 < pairs.length
              ? pairs[index + 1][0]
              : Infinity,

            3,
            0.75
          )
        )
    )
  );
}


// ==================================================
// FÜR ELISE (Beethoven, public domain)
//
// Written from the score, like the classical
// songs in Magic Tiles. There is no MP3: the
// backing track (left hand + a light beat) is
// generated by audio.js from the same score,
// so the beat and the notes cannot drift apart.
//
// The player's hits play the melody. On Easy
// and Medium each tile also plays the melody
// notes up to the next tile ("fills"), so the
// tune is complete whenever the player hits.
//
// Time signature: 3/8
// One beat = one eighth note (120 BPM).
// Positions inside a measure are counted in
// sixteenth notes, 0–5.
// ==================================================

const FUR_ELISE_MEASURES =
  Object.freeze({

    // Last intro measure: the "E – D#" pickup.
    pickup: {
      melody: [[4, "E5"], [5, "D#5"]],
      left: [[0, "A2"], [1, "E3"], [2, "A3"]]
    },

    intro: {
      melody: [],
      left: [[0, "A2"], [1, "E3"], [2, "A3"]]
    },

    // ---------- A section ----------

    a1: {
      melody: [[0, "E5"], [1, "D#5"], [2, "E5"], [3, "B4"], [4, "D5"], [5, "C5"]],
      left: []
    },

    a2: {
      melody: [[0, "A4"], [3, "C4"], [4, "E4"], [5, "A4"]],
      left: [[0, "A2"], [1, "E3"], [2, "A3"]]
    },

    a3: {
      melody: [[0, "B4"], [3, "E4"], [4, "G#4"], [5, "B4"]],
      left: [[0, "E2"], [1, "E3"], [2, "G#3"]]
    },

    a4: {
      melody: [[0, "C5"], [3, "E4"], [4, "E5"], [5, "D#5"]],
      left: [[0, "A2"], [1, "E3"], [2, "A3"]]
    },

    a7: {
      melody: [[0, "B4"], [3, "E4"], [4, "C5"], [5, "B4"]],
      left: [[0, "E2"], [1, "E3"], [2, "G#3"]]
    },

    // First ending: leads back to the start.
    a8Repeat: {
      melody: [[0, "A4"], [4, "E5"], [5, "D#5"]],
      left: [[0, "A2"], [1, "E3"], [2, "A3"]]
    },

    // Second ending: leads into the B section.
    a8ToB: {
      melody: [[0, "A4"], [3, "B4"], [4, "C5"], [5, "D5"]],
      left: [[0, "A2"], [1, "E3"], [2, "A3"]]
    },

    // Final measure of the song.
    a8End: {
      melody: [[0, "A4"]],
      left: [[0, "A2"], [1, "E3"], [2, "A3"]]
    },

    // ---------- B section ----------

    b1: {
      melody: [[0, "E5"], [3, "G4"], [4, "F5"], [5, "E5"]],
      left: [[0, "C3"], [1, "G3"], [2, "C4"]]
    },

    b2: {
      melody: [[0, "D5"], [3, "F4"], [4, "E5"], [5, "D5"]],
      left: [[0, "G2"], [1, "G3"], [2, "B3"]]
    },

    b3: {
      melody: [[0, "C5"], [3, "E4"], [4, "D5"], [5, "C5"]],
      left: [[0, "A2"], [1, "E3"], [2, "A3"]]
    },

    // Shortened bridge back to the theme.
    b4: {
      melody: [[0, "B4"], [4, "E5"], [5, "D#5"]],
      left: [[0, "E2"], [1, "E3"], [2, "E4"]]
    }

  });


const FUR_ELISE_THEME =
  ["a1", "a2", "a3", "a4", "a1", "a2", "a7"];


const FUR_ELISE_PASS = [
  ...FUR_ELISE_THEME, "a8Repeat",
  ...FUR_ELISE_THEME, "a8ToB",
  "b1", "b2", "b3", "b4",
  ...FUR_ELISE_THEME
];


// Played twice (~88s), ending on the final A.
const FUR_ELISE_FORM = [
  "intro", "pickup",
  ...FUR_ELISE_PASS, "a8Repeat",
  ...FUR_ELISE_PASS, "a8End"
];


/*
 * Converts the measure list into beat
 * positions:
 *
 * melody – what the player plays
 * left   – backing piano
 * drums  – kick on each measure, hi-hat
 *          on the other two eighth notes
 */
function buildScore(
  form,
  measures,
  beatsPerMeasure
) {
  const melody = [];
  const left = [];
  const drums = [];

  form.forEach(
    (measureName, index) => {
      const measure =
        measures[measureName];

      const measureStart =
        1 + index * beatsPerMeasure;

      const toBeat =
        (sixteenth) =>
          measureStart + sixteenth / 2;

      measure.melody.forEach(
        ([sixteenth, note]) => {
          melody.push({
            beat: toBeat(sixteenth),
            note
          });
        }
      );

      measure.left.forEach(
        ([sixteenth, note]) => {
          left.push({
            beat: toBeat(sixteenth),
            note
          });
        }
      );

      drums.push(
        { beat: measureStart, sound: "kick" },
        { beat: measureStart + 1, sound: "hat" },
        { beat: measureStart + 2, sound: "hat" }
      );
    }
  );

  return { melody, left, drums };
}


/*
 * Builds a chart from the melody.
 *
 * keep(note, tiles) chooses which melody
 * notes become tiles, given the tiles
 * chosen so far. The melody notes
 * between one tile and the next are
 * stored as that tile's fills.
 */
function buildMelodyChart(
  melody,
  keep
) {
  const tiles = [];

  melody.forEach(
    (note) => {
      if (keep(note, tiles)) {
        tiles.push(note);
      }
    }
  );

  return Object.freeze(
    tiles.map(
      (tile, index) => {
        const nextBeat =
          index + 1 < tiles.length
            ? tiles[index + 1].beat
            : Infinity;

        const fills =
          melody
            .filter(
              (note) =>
                note.beat > tile.beat &&
                note.beat < nextBeat
            )
            .map(
              (note) =>
                Object.freeze({ ...note })
            );

        /*
         * The melody moves on at the next
         * melody note, not the next tile,
         * so a held note stops there.
         */
        const nextMelodyBeat =
          fills.length > 0
            ? fills[0].beat
            : nextBeat;


        return Object.freeze({
          beat: tile.beat,
          note: tile.note,

          holdBeats:
            holdLength(
              tile.beat,
              nextMelodyBeat,
              1.5,
              0.5
            ),

          fills: Object.freeze(fills)
        });
      }
    )
  );
}


const FUR_ELISE_SCORE =
  buildScore(
    FUR_ELISE_FORM,
    FUR_ELISE_MEASURES,
    3
  );


const isMeasureStart =
  (note) =>
    (note.beat - 1) % 3 === 0;


const isEighthNote =
  (note) =>
    Number.isInteger(note.beat);


// Easy: the first note of each measure.
const FUR_ELISE_EASY_CHART =
  buildMelodyChart(
    FUR_ELISE_SCORE.melody,
    isMeasureStart
  );

// Medium: every eighth note.
const FUR_ELISE_MEDIUM_CHART =
  buildMelodyChart(
    FUR_ELISE_SCORE.melody,
    isEighthNote
  );

/*
 * Hard: melody notes where a sixteenth
 * note gap is always followed by at
 * least an eighth note (quick notes
 * come in pairs, not streams). The
 * notes in between play as fills.
 */
const FUR_ELISE_HARD_CHART =
  buildMelodyChart(
    FUR_ELISE_SCORE.melody,
    (note, tiles) =>
      tiles.length < 2 ||
      note.beat -
        tiles[tiles.length - 2].beat >= 1.5
  );


export const FUR_ELISE =
  Object.freeze({

    id:
      "fur-elise",

    title:
      "Für Elise",

    artist:
      "Ludwig van Beethoven",

    /*
     * No audioPath: audio.js renders
     * this backing track instead.
     */
    backing:
      Object.freeze({
        left: FUR_ELISE_SCORE.left,
        drums: FUR_ELISE_SCORE.drums
      }),

    bpm:
      120,

    key:
      "A minor",

    timeSignature:
      Object.freeze([
        3,
        8
      ]),

    /*
     * Beat 1 starts 0.3s into the
     * generated audio, so the first note
     * (the pickup on beat 5) has its full
     * fall time.
     */
    offset:
      0.3,

    difficulties:
      Object.freeze({

        easy:
          FUR_ELISE_EASY_CHART,

        medium:
          FUR_ELISE_MEDIUM_CHART,

        hard:
          FUR_ELISE_HARD_CHART

      })

  });


// ==================================================
// SONG 1
//
// OUTBYTE
//
// BPM: 119.75
// Key: C major (notes use C D E F G A B)
// Time signature: 4/4
//
// Charted from beat 5 to beat 192 (~97s).
// The drums enter at beat 33.
// ==================================================

const OUTBYTE_EASY_CHART =
  buildChart([
    [12, "C5"], [17, "G4"], [21, "G4"], [25, "E4"], [29, "E4"], [33, "E4"],
    [36, "C4"], [40, "C4"], [54, "B4"], [63, "A4"], [65, "E4"], [67, "A4"],
    [69, "E4"], [71, "B4"], [73, "C5"], [75, "F5"], [77, "C5"], [79, "C5"],
    [81, "G4"], [84, "D4"], [86, "G4"], [88, "G4"], [91, "B4"], [93, "E5"],
    [96, "C5"], [98, "C5"], [100, "C5"], [102, "C5"], [105, "F5"], [107, "C5"],
    [109, "C5"], [111, "C5"], [113, "G4"], [116, "D4"], [118, "B4"], [120, "G4"],
    [123, "B4"], [125, "E4"], [127, "B4"], [129, "E5"], [132, "C5"], [134, "C5"],
    [137, "C5"], [139, "F5"], [141, "C5"], [143, "C5"], [145, "G4"], [147, "G4"],
    [149, "G4"], [151, "C5"], [153, "E5"], [155, "A5"], [158, "A5"], [160, "A5"],
    [162, "A5"], [164, "A5"], [166, "A5"], [169, "C5"], [171, "C5"], [173, "C5"],
    [176, "C5"], [179, "D4"], [182, "D4"], [185, "E4"], [188, "C4"], [190, "A4"],
    [192, "A4"]
  ]);

const OUTBYTE_MEDIUM_CHART =
  buildChart([
    [12, "C5"], [17, "G4"], [21, "G4"], [25, "E4"], [29, "E4"], [33, "E4"],
    [36, "C4"], [40, "C4"], [45.5, "C4"], [52.5, "G4"], [54, "B4"], [56.5, "D4"],
    [63, "A4"], [65, "E4"], [66, "C4"], [67, "A4"], [69, "E4"], [70, "C4"],
    [71, "B4"], [72, "C5"], [73, "C5"], [74, "C5"], [75, "F5"], [77, "C5"],
    [78, "C5"], [79, "C5"], [80, "C5"], [81, "G4"], [83, "G4"], [84, "D4"],
    [85, "G4"], [86, "G4"], [87, "C5"], [88, "G4"], [89, "E4"], [91, "B4"],
    [93, "E5"], [94, "E5"], [95, "B4"], [96, "C5"], [97, "E5"], [98, "C5"],
    [99, "B4"], [100, "C5"], [101, "E5"], [102, "C5"], [103.5, "E5"], [105, "F5"],
    [106, "C5"], [107, "C5"], [109, "C5"], [111, "C5"], [112, "C5"], [113, "G4"],
    [115, "G4"], [116, "D4"], [117, "G4"], [118, "B4"], [119, "C5"], [120, "G4"],
    [121, "E4"], [123, "B4"], [125, "E4"], [127, "B4"], [129, "E5"], [130, "C5"],
    [131, "B4"], [132, "C5"], [134, "C5"], [135.5, "A4"], [137, "C5"], [139, "F5"],
    [140, "A5"], [141, "C5"], [143, "C5"], [145, "G4"], [147, "G4"], [149, "G4"],
    [150, "G4"], [151, "C5"], [152, "D5"], [153, "E5"], [154, "A5"], [155, "A5"],
    [156, "C5"], [157, "E5"], [158, "A5"], [159, "A5"], [160, "A5"], [161, "E5"],
    [162, "A5"], [164, "A5"], [165, "E5"], [166, "A5"], [167.5, "A5"], [169, "C5"],
    [171, "C5"], [172, "C5"], [173, "C5"], [174, "C5"], [176, "C5"], [179, "D4"],
    [180, "D4"], [181, "G4"], [182, "D4"], [183.5, "B4"], [185, "E4"], [187, "E4"],
    [188, "C4"], [189, "A4"], [190, "A4"], [192, "A4"]
  ]);

const OUTBYTE_HARD_CHART =
  buildChart([
    [7.5, "E5"], [11.5, "A5"], [12, "C5"], [14, "C5"], [15, "B4"], [17, "G4"],
    [20.5, "G4"], [21, "G4"], [24.5, "G4"], [25, "E4"], [26, "C4"], [28.5, "A4"],
    [29, "E4"], [30, "C4"], [33, "E4"], [36, "C4"], [37.5, "E4"], [38, "C4"],
    [39.5, "E4"], [40, "C4"], [41, "C4"], [42.5, "F4"], [43.5, "F4"], [45, "C4"],
    [45.5, "C4"], [46.5, "C4"], [49, "G4"], [49.5, "G4"], [52.5, "G4"], [54, "B4"],
    [55, "G4"], [56.5, "D4"], [57, "E4"], [59.5, "A4"], [62.5, "A4"], [63, "A4"],
    [65, "E4"], [66, "C4"], [67, "A4"], [67.5, "A4"], [68.5, "A4"], [69, "E4"],
    [70, "C4"], [71, "B4"], [72, "C5"], [73, "C5"], [74, "C5"], [75, "F5"],
    [75.5, "F5"], [76.5, "C5"], [77, "C5"], [78, "C5"], [79, "C5"], [80, "C5"],
    [81, "G4"], [83, "G4"], [84, "D4"], [85, "G4"], [86, "G4"], [87, "C5"],
    [88, "G4"], [89, "E4"], [89.5, "E4"], [91, "B4"], [91.5, "E5"], [93, "E5"],
    [94, "E5"], [95, "B4"], [96, "C5"], [97, "E5"], [98, "C5"], [99, "B4"],
    [100, "C5"], [101, "E5"], [102, "C5"], [103, "C5"], [103.5, "E5"], [104.5, "A5"],
    [105, "F5"], [106, "C5"], [107, "C5"], [107.5, "F5"], [109, "C5"], [109.5, "C5"],
    [110.5, "C5"], [111, "C5"], [112, "C5"], [113, "G4"], [113.5, "G4"], [114.5, "G4"],
    [115, "G4"], [116, "D4"], [117, "G4"], [118, "B4"], [119, "C5"], [120, "G4"],
    [121, "E4"], [122, "C4"], [123, "B4"], [123.5, "A4"], [124.5, "E4"], [125, "E4"],
    [127, "B4"], [128, "C5"], [129, "E5"], [130, "C5"], [131, "B4"], [132, "C5"],
    [133, "E5"], [134, "C5"], [134.5, "A4"], [135.5, "A4"], [136, "C5"], [137, "C5"],
    [138, "C5"], [139, "F5"], [140, "A5"], [141, "C5"], [142, "A4"], [143, "C5"],
    [144, "C5"], [145, "G4"], [146, "B4"], [147, "G4"], [147.5, "G4"], [148.5, "G4"],
    [149, "G4"], [150, "G4"], [151, "C5"], [152, "D5"], [153, "E5"], [154, "A5"],
    [155, "A5"], [156, "C5"], [157, "E5"], [158, "A5"], [159, "A5"], [160, "A5"],
    [161, "E5"], [162, "A5"], [163.5, "A5"], [164, "A5"], [165, "E5"], [166, "A5"],
    [167, "A5"], [167.5, "A5"], [169, "C5"], [170, "C5"], [171, "C5"], [172, "C5"],
    [173, "C5"], [174, "C5"], [175, "A4"], [176, "C5"], [177, "G4"], [179, "D4"],
    [180, "D4"], [181, "G4"], [182, "D4"], [183.5, "B4"], [184, "G4"], [185, "E4"],
    [186, "C4"], [187, "E4"], [188, "C4"], [189, "A4"], [190, "A4"], [191, "A4"],
    [192, "A4"]
  ]);


// ==================================================
// SONG 2
//
// SHADOWS BEHIND NEON
//
// BPM: 104.76
// Key: C minor (notes use C D D# F G G# A#)
// Time signature: 4/4
//
// Charted from beat 5 to beat 184 (~106s).
// Breakdown around beats 65–80, quieter
// outro from beat 145.
// ==================================================

const SHADOWS_EASY_CHART =
  buildChart([
    [7, "C4"], [10, "D#4"], [12, "A#4"], [15, "F4"], [18, "C4"], [20, "C4"],
    [22, "C5"], [24, "C5"], [26, "C5"], [28, "F5"], [30, "A#5"], [33, "C5"],
    [35, "C5"], [38, "F5"], [41, "G#5"], [43, "G#5"], [46, "C5"], [48, "C5"],
    [52, "C5"], [54, "F5"], [57, "G#5"], [60, "C5"], [62, "C5"], [64, "C5"],
    [68, "C5"], [70, "C5"], [72, "C5"], [74, "G5"], [76, "G4"], [78, "C4"],
    [80, "C5"], [83, "C5"], [87, "G5"], [90, "G#5"], [92, "A#5"], [96, "D#5"],
    [99, "C5"], [102, "C5"], [104, "G#4"], [106, "G#4"], [108, "A#4"], [110, "F4"],
    [113, "C4"], [115, "C4"], [118, "G4"], [120, "D4"], [122, "C4"], [124, "A#4"],
    [130, "C5"], [133, "C5"], [135, "D#4"], [138, "D4"], [140, "C4"], [143, "A#4"],
    [147, "C5"], [149, "C5"], [153, "C5"], [156, "C5"], [158, "C5"], [160, "C5"],
    [172, "A#5"], [174, "F5"], [178, "C5"], [181, "D#5"]
  ]);

const SHADOWS_MEDIUM_CHART =
  buildChart([
    [6, "C4"], [7, "C4"], [8.5, "D4"], [10, "D#4"], [11, "C4"], [12, "A#4"],
    [14, "A#4"], [15, "F4"], [16, "C4"], [18, "C4"], [19, "C4"], [20, "C4"],
    [21, "G4"], [22, "C5"], [23, "C5"], [24, "C5"], [25, "C5"], [26, "C5"],
    [27, "C5"], [28, "F5"], [29, "A#5"], [30, "A#5"], [31.5, "F5"], [33, "C5"],
    [35, "C5"], [36, "F5"], [38, "F5"], [39.5, "D#5"], [41, "G#5"], [42, "G#5"],
    [43, "G#5"], [46, "C5"], [47, "C5"], [48, "C5"], [49.5, "C5"], [50.5, "C5"],
    [52, "C5"], [53, "C5"], [54, "F5"], [55.5, "D#5"], [57, "G#5"], [58.5, "G#5"],
    [60, "C5"], [62, "C5"], [63, "C5"], [64, "C5"], [66.5, "C5"], [68, "C5"],
    [70, "C5"], [72, "C5"], [74, "G5"], [75, "C5"], [76, "G4"], [78, "C4"],
    [80, "C5"], [81, "C5"], [83, "C5"], [84.5, "C5"], [87, "G5"], [88, "G#5"],
    [90, "G#5"], [91, "G#5"], [92, "A#5"], [93.5, "G5"], [96, "D#5"], [99, "C5"],
    [100.5, "C5"], [102, "C5"], [104, "G#4"], [106, "G#4"], [108, "A#4"], [110, "F4"],
    [113, "C4"], [115, "C4"], [116, "C4"], [117, "C4"], [118, "G4"], [120, "D4"],
    [121, "D#4"], [122, "C4"], [124, "A#4"], [129, "C5"], [130, "C5"], [131.5, "C5"],
    [133, "C5"], [134, "G4"], [135, "D#4"], [138, "D4"], [140, "C4"], [141, "C4"],
    [143, "A#4"], [144, "C5"], [147, "C5"], [149, "C5"], [150.5, "C5"], [151.5, "C5"],
    [153, "C5"], [154.5, "C5"], [156, "C5"], [158, "C5"], [160, "C5"], [165.5, "D#5"],
    [169.5, "G#5"], [172, "A#5"], [174, "F5"], [178, "C5"], [181, "D#5"], [182.5, "G4"]
  ]);

const SHADOWS_HARD_CHART =
  buildChart([
    [6, "C4"], [7, "C4"], [8, "C4"], [8.5, "D4"], [9.5, "D#4"], [10, "D#4"],
    [11, "C4"], [12, "A#4"], [12.5, "D5"], [14, "A#4"], [15, "F4"], [16, "C4"],
    [16.5, "C4"], [17.5, "D#4"], [18, "C4"], [19, "C4"], [20, "C4"], [21, "G4"],
    [22, "C5"], [23, "C5"], [24, "C5"], [25, "C5"], [26, "C5"], [27, "C5"],
    [28, "F5"], [29, "A#5"], [30, "A#5"], [30.5, "D5"], [31.5, "F5"], [33, "C5"],
    [33.5, "D#5"], [35, "C5"], [36, "F5"], [37, "C5"], [38, "F5"], [38.5, "D5"],
    [39.5, "D#5"], [41, "G#5"], [42, "G#5"], [43, "G#5"], [43.5, "C5"], [44.5, "D5"],
    [45.5, "D#5"], [46, "C5"], [47, "C5"], [48, "C5"], [49, "C5"], [49.5, "C5"],
    [50.5, "C5"], [51, "C5"], [52, "C5"], [53, "C5"], [54, "F5"], [54.5, "D5"],
    [55.5, "D#5"], [56.5, "G#5"], [57, "G#5"], [58, "G#5"], [58.5, "G#5"], [59.5, "D#5"],
    [60, "C5"], [61.5, "C5"], [62, "C5"], [63, "C5"], [64, "C5"], [66.5, "C5"],
    [67.5, "D#5"], [68, "C5"], [69.5, "D#5"], [70, "C5"], [71.5, "D#5"], [72, "C5"],
    [73.5, "D#5"], [74, "G5"], [75, "C5"], [76, "G4"], [77, "D4"], [78, "C4"],
    [79, "A#4"], [80, "C5"], [81, "C5"], [83, "C5"], [83.5, "D#5"], [84.5, "C5"],
    [85.5, "D#5"], [86.5, "D5"], [87, "G5"], [88, "G#5"], [89.5, "G#5"], [90, "G#5"],
    [91, "G#5"], [92, "A#5"], [93, "G5"], [93.5, "G5"], [94.5, "F5"], [95.5, "D#5"],
    [96, "D#5"], [99, "C5"], [99.5, "C5"], [100.5, "C5"], [101.5, "D#5"], [102, "C5"],
    [103.5, "G4"], [104, "G#4"], [106, "G#4"], [106.5, "G#4"], [108, "A#4"], [108.5, "A#4"],
    [110, "F4"], [110.5, "F4"], [112.5, "C4"], [113, "C4"], [114.5, "C4"], [115, "C4"],
    [116, "C4"], [117, "C4"], [118, "G4"], [118.5, "F4"], [119.5, "D4"], [120, "D4"],
    [121, "D#4"], [122, "C4"], [122.5, "C4"], [123.5, "C4"], [124, "A#4"], [129, "C5"],
    [130, "C5"], [131.5, "C5"], [132.5, "C5"], [133, "C5"], [134, "G4"], [135, "D#4"],
    [136, "D4"], [138, "D4"], [138.5, "D4"], [140, "C4"], [141, "C4"], [141.5, "C4"],
    [143, "A#4"], [144, "C5"], [147, "C5"], [149, "C5"], [150.5, "C5"], [151.5, "C5"],
    [152.5, "C5"], [153, "C5"], [154.5, "C5"], [155.5, "D#5"], [156, "C5"], [158, "C5"],
    [160, "C5"], [163.5, "D#5"], [165.5, "D#5"], [169.5, "G#5"], [172, "A#5"], [172.5, "A#5"],
    [174, "F5"], [175, "F5"], [178, "C5"], [181, "D#5"], [181.5, "C5"], [182.5, "G4"]
  ]);


// ==================================================
// SONG CONFIGURATION 1
//
// OUTBYTE
// ==================================================

export const OUTBYTE =
  Object.freeze({

    id:
      "outbyte",

    title:
      "Outbyte",

    artist:
      "Beat Mekanik",

    audioPath:
      "./audio/practice-song.mp3",

    /*
     * Measured from the audio. At exactly
     * 120 the notes drift ~0.45s late by
     * the end of the track.
     */
    bpm:
      119.75,

    key:
      "C major",

    timeSignature:
      Object.freeze([
        4,
        4
      ]),

    /*
     * First musical beat is approximately
     * 1.02 seconds into the audio.
     *
     * Gameplay begins from Beat 5,
     * providing reaction time before
     * the first target reaches the keyboard.
     */
    offset:
      1.02,

    difficulties:
      Object.freeze({

        easy:
          OUTBYTE_EASY_CHART,

        medium:
          OUTBYTE_MEDIUM_CHART,

        hard:
          OUTBYTE_HARD_CHART

      })

  });


// ==================================================
// SONG CONFIGURATION 2
//
// SHADOWS BEHIND NEON
// ==================================================

export const SHADOWS_BEHIND_NEON =
  Object.freeze({

    id:
      "shadows-behind-neon",

    title:
      "Shadows Behind Neon",

    artist:
      "StockTune",

    audioPath:
      "./audio/shadows-behind-neon.mp3",

    /*
     * Measured from the hi-hats, which
     * play steady eighth notes. The
     * overall loudness of this track
     * gives a misleading 104.15, which
     * drifts ~0.5s out by the end.
     */
    bpm:
      104.76,

    key:
      "C minor",

    timeSignature:
      Object.freeze([
        4,
        4
      ]),

    /*
     * First beat at 0.44 seconds, where
     * the kick and snare land (the
     * hi-hats also play half a beat
     * later, at 0.154 + 0.286s steps).
     *
     * If the whole chart feels consistently
     * early or late, adjust this value.
     */
    offset:
      0.44,

    difficulties:
      Object.freeze({

        easy:
          SHADOWS_EASY_CHART,

        medium:
          SHADOWS_MEDIUM_CHART,

        hard:
          SHADOWS_HARD_CHART

      })

  });


// ==================================================
// COMPLETE SONG LIBRARY
// ==================================================

export const SONGS =
  Object.freeze({

    "fur-elise":
      FUR_ELISE,

    outbyte:
      OUTBYTE,

    "shadows-behind-neon":
      SHADOWS_BEHIND_NEON

  });


// ==================================================
// GET SONG BY ID
// ==================================================

export function getSongById(
  songId
) {

  return (
    SONGS[
      songId
    ] ||
    null
  );
}


// ==================================================
// GET ALL SONGS
// ==================================================

export function getAllSongs() {

  return Object.values(
    SONGS
  );
}


// ==================================================
// BACKWARDS COMPATIBILITY
// ==================================================

/*
 * Retained because older parts of the
 * project may still import PRACTICE_SONG.
 */
export const PRACTICE_SONG =
  OUTBYTE;